tinyMCE.addI18n('zh.advanced',{
style_select:"样式",
font_size:"字号",
fontdefault:"字体",
block:"格式",
paragraph:"段落",
div:"层（Div）",
address:"地址",
pre:"预设",
h1:"标题 1",
h2:"标题 2",
h3:"标题 3",
h4:"标题 4",
h5:"标题 5",
h6:"标题 6",
blockquote:"块引用",
code:"代码",
samp:"代码示例",
dt:"定义术语",
dd:"定义描述",
span:"块（Span）",
bold_desc:"加粗 (Ctrl+B)",
italic_desc:"斜体 (Ctrl+I)",
underline_desc:"下划线 (Ctrl+U)",
striketrough_desc:"删除线",
justifyleft_desc:"左对齐",
justifycenter_desc:"居中",
justifyright_desc:"右对齐",
justifyfull_desc:"分散对齐",
bullist_desc:"无序列表",
numlist_desc:"有序列表",
outdent_desc:"减少缩进",
indent_desc:"增加缩进",
undo_desc:"撤消 (Ctrl+Z)",
redo_desc:"恢复 (Ctrl+Y)",
link_desc:"插入/编辑链接",
unlink_desc:"取消链接",
image_desc:"插入/编辑图片",
cleanup_desc:"清理HTML标记",
code_desc:"编辑HTML源代码",
sub_desc:"下标",
sup_desc:"上标",
hr_desc:"插入水平线",
removeformat_desc:"删除格式",
custom1_desc:"您的自定义的描述在这里",
forecolor_desc:"选择文字颜色",
backcolor_desc:"选择背景颜色",
charmap_desc:"插入自定义字符",
visualaid_desc:"切换指引/不可见元素",
anchor_desc:"插入/编辑锚点",
cut_desc:"剪切",
copy_desc:"复制",
paste_desc:"粘贴",
image_props_desc:"图像属性",
newdocument_desc:"新文件",
help_desc:"帮助",
blockquote_desc:"块引用",
clipboard_msg:"Mozilla和Firefox浏览器不支持剪切、复制和粘贴功能，请使用快捷键操作。\r\n你想了解更多有关此问题的信息吗？",
path:"路径",
newdocument:"你是否确定要清除所有的内容?",
toolbar_focus:"跳转到工具按钮 - Alt+Q, 跳转到编辑器 - Alt-Z, 跳转到元素的路径 - Alt-X",
more_colors:"更多颜色",
	
// Accessibility Strings
shortcuts_desc:'无障碍帮助',
help_shortcut:'. Press ALT F10 for toolbar. Press ALT 0 for help.',
rich_text_area:"富文本区域",
toolbar:"工具栏"
});